- name: Pasang Prometheus
  hosts: node1
  become: true
  roles:
    - prometheus.prometheus.prometheus

  vars:
    prometheus_scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: node_exporter
        static_configs:
          - targets:
              - '10.30.1.30:9100'
              - '10.30.1.116:9100'